spring:
  datasource:
    url: "jdbc:h2:mem:springdb;DB_CLOSE_DELAY=-1"
    username: "noway"
    password: "spring-security-painful"
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true