---

spring:
  application:
    name: app
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: "dev"

server:
  port: 8089

logging:
  level:
    root: INFO